### Propiedad asociativa

In [20]:
import numpy as np
A = np.array([[1,2],[5,6],[7,8]])
B = np.array([[1,2],[4,5]])
C = np.array([[4,5],[6,7]])

In [21]:
A.dot(B.dot(C))

array([[108, 129],
       [356, 425],
       [480, 573]])

In [22]:
A.dot(B).dot(C)

array([[108, 129],
       [356, 425],
       [480, 573]])

### Propiedad distributiva
A * ( B + C ) = A*B + A*C 

In [32]:
A.dot(B + C) == A.dot(B) + A.dot(C)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

### Propiedad conmutativa

In [35]:
B.dot(C) == C.dot(B)

array([[False, False],
       [False, False]])

In [ ]:
### TRansposición