In [4]:
import numpy as np

escalar = 4.5667
vector = np.array([2,3,4,5,6,7])
matriz = np.array([[1,2,3,4],[5,6,7,8]])
tensor = np.array([
    [[255,255,255],[255,255,255],[255,255,255]],
    [[128,128,128],[128,128,128],[128,128,128]],
])

### Transposicion

In [6]:
vector.T

array([2, 3, 4, 5, 6, 7])

In [7]:
matriz.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [9]:
tensor.T

array([[[255, 128],
        [255, 128],
        [255, 128]],

       [[255, 128],
        [255, 128],
        [255, 128]],

       [[255, 128],
        [255, 128],
        [255, 128]]])

### Suma 

In [11]:
A = np.array([[1,2,3,4],[5,6,7,8]])
B = np.array([[10,20,30,40],[50,60,70,80]])
A + B 

array([[11, 22, 33, 44],
       [55, 66, 77, 88]])

In [12]:
A + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Broadcasting

In [18]:
C = np.array([[1,2,3,4]])
A + C

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

### Producto

In [19]:
vector = np.array([2,3,4,5])
matriz * vector

array([[ 2,  6, 12, 20],
       [10, 18, 28, 40]])

### Producto interno

In [21]:
matriz.dot(vector)

array([40, 96])

In [52]:
producto_interno = []
for i in range(matriz.shape[0]):
    producto_interno.append(np.sum([number * vector[index] for index, number in enumerate(matriz[i])]))
    
print(producto_interno)

[40, 96]


### propiedades de matrices